import { useState } from "react";

import { Button } from "@harness/design-system";

import { updateStory, type Story } from "../api/editorBffClient";

const EDITED_BY = import.meta.env.VITE_CURRENT_USER_EMAIL || "reviewer@example.com";

export interface StoryEditFormProps {
  story: Story;
  onSaved: (story: Story) => void;
  onCancel: () => void;
}

export function StoryEditForm({ story, onSaved, onCancel }: StoryEditFormProps) {
  const [title, setTitle] = useState(story.title);
  const [description, setDescription] = useState(story.description);
  const [acceptanceCriteria, setAcceptanceCriteria] = useState<string[]>([...story.acceptance_criteria]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function updateCriterion(index: number, value: string) {
    setAcceptanceCriteria((prev) => prev.map((c, i) => (i === index ? value : c)));
  }

  function removeCriterion(index: number) {
    setAcceptanceCriteria((prev) => prev.filter((_, i) => i !== index));
  }

  function addCriterion() {
    setAcceptanceCriteria((prev) => [...prev, ""]);
  }

  async function handleSave() {
    setSaving(true);
    setError(null);
    try {
      await updateStory(story._id, {
        title,
        description,
        acceptance_criteria: acceptanceCriteria.filter((c) => c.trim().length > 0),
        edited_by: EDITED_BY,
      });
      onSaved({
        ...story,
        title,
        description,
        acceptance_criteria: acceptanceCriteria.filter((c) => c.trim().length > 0),
        edited_by_human: true,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  }

  return (
    <div>
      <label htmlFor={`title-${story._id}`}>Title</label>
      <input id={`title-${story._id}`} value={title} onChange={(e) => setTitle(e.target.value)} />

      <label htmlFor={`description-${story._id}`}>Description</label>
      <textarea
        id={`description-${story._id}`}
        value={description}
        onChange={(e) => setDescription(e.target.value)}
      />

      <h4>Acceptance Criteria</h4>
      {acceptanceCriteria.map((criterion, index) => (
        <div key={index}>
          <input
            aria-label={`Acceptance criterion ${index + 1}`}
            value={criterion}
            onChange={(e) => updateCriterion(index, e.target.value)}
          />
          <button type="button" onClick={() => removeCriterion(index)}>
            Remove
          </button>
        </div>
      ))}
      <button type="button" onClick={addCriterion}>
        Add acceptance criterion
      </button>

      <h4>Traceability (read-only)</h4>
      <ul>
        {story.source_program_ids.map((sourceId) => (
          <li key={sourceId}>{sourceId}</li>
        ))}
      </ul>
      <p>Generated by: {story.generated_by_agent}</p>

      <div style={{ display: "flex", gap: "0.5rem" }}>
        <Button variant="primary" onClick={handleSave} disabled={saving}>
          {saving ? "Saving…" : "Save"}
        </Button>
        <Button variant="secondary" onClick={onCancel} disabled={saving}>
          Cancel
        </Button>
      </div>

      {error && <p role="alert">{error}</p>}
    </div>
  );
}
